### ISSUE TITLE
Acabar el juego

### ISSUE THREAD

**Issue by nasivuela** [Adalab/dorcas-s2-evaluacion-intermedia-estherpato#1]
Buen trabajo Esther!

El HTML está espartano pero suficiente para realizar el ejercicio, tu lógica tiene muy buena pinta!!

Te dejo algunas sugerencias con detalle a mejorar:

- Si declaramos las variables arriba de cada scope, mejor que mejor.
- Se ha quedado el contador en el tintero, dale caña, si te surge alguna duda me comentas.
- BONUS extra: ¿Que pasaría si la usuaria pone un valor no númerico en el input? ¿Y si fuera uno númerico mayor que 100 o menor que 1?

A por ello!

**Comment by estherpato** [comment]
Variables arriba ✓
Contador ✓ - intenté declarar el contador en una función diferente, pero no me funcionaba.
Si se introduce un valor no numérico, la consola te muestra el valor y el contador funciona, pero el feedback no cambia (puesto que está declarado para un valor numérico).
Con un valor > 100, el juego indica que te has pasado y en caso de ser menor que uno, te dice que no llegas. 
He conseguido que al introducir algo que no sea un número el feedback te diga que metas un número, pero para valores mayores de 100 o menores que 1 no lo coge.

**Comment by nasivuela** [comment]
@estherpato recuerda que las condiciones en una estructura if/esle se leen de arriba hacía abajo, y en cuanto se cumple una ya no se comprueba ninguna otra. 
Mira tu código y piensa si la usuaria introduce por ejemplo el número 120, ¿cual es la primera condición que se cumplira? ¿cual es la primera que a ti te gustaría que se cumpliera con un valor de mayor que 100? Animo!

**Comment by estherpato** [comment]
Toda la razón! Ya está listo

**Comment by nasivuela** [comment]
![](https://media.giphy.com/media/c79tfTvN76sWA/giphy.gif)
